// <auto-generated />
using LeetcodeAutoBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeetcodeAutoBot.Migrations
{
    [DbContext(typeof(LeetcodeAutoBotDbContext))]
    [Migration("20260105025235_RemoveDevice")]
    partial class RemoveDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("LeetcodeAutoBot.Database.Models.Cookie", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "domain");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Expires")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "expires");

                    b.Property<bool?>("HttpOnly")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "httpOnly");

                    b.Property<string>("PartitionKey")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "partitionKey");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "path");

                    b.Property<int?>("SameSite")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "sameSite");

                    b.Property<bool?>("Secure")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "secure");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Name", "Domain", "AccountId");

                    b.ToTable("Cookies");
                });

            modelBuilder.Entity("LeetcodeAutoBot.Database.Models.LocalStorageEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "AccountId");

                    b.ToTable("LocalStorageEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
